project:
  type: website
  output-dir: docs

website:
  title: "The Machine Learning Engineer"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Mikaelssilva
      - icon: instagram
        href: https://www.instagram.com/mikael.ssilva20/

format:
  html:
    theme:
      - solar
      - brand
    css: styles.css
    includes:
      after-body: subscribe.html
