project:
  type: website
  output-dir: docs

website:
  title: "The Machine Learning Engineer"
  
  navbar:
    background: dark
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd

    right:
      - icon: github
        href: https://github.com/Mikaelssilva/TheMachineEngineerBlog
      - icon: instagram
        href: https://www.instagram.com/mikael.ssilva20/
      - icon: linkedin
        href: https://www.linkedin.com/in/mikaelssilva

  page-footer:
    background: dark
    left: |
      © 2025 The Machine Learning Engineer. Todos os direitos reservados.
    right: |
      Feito com ❤️ usando [Quarto](https://quarto.org)

format:
  html:
    theme: 
      - solar
    css: styles.css
    toc: true
    toc-location: right
    code-fold: false
    code-tools: false
    highlight-style: github-dark
    smooth-scroll: true
    page-layout: full
    title-block-banner: true

# Configurações de busca
search: true

# Comentários
comments:
  giscus:
    repo: Mikaelssilva/TheMachineEngineerBlog
    repo-id: '1027959386'    
    category: "Comments"
    category-id: "DIC_kwDOF-5fGM4CbQw9"
    mapping: pathname
    reactions-enabled: true
    theme: transparent_dark