project:
  type: website
  output-dir: docs

website:
  title: "The Machine Learning Engineer"
  reader-mode: true
  favicon: favcon.png
  
  navbar:
    logo: favcon.png
    background: dark
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: 'Menu'
        menu:
          - text: 'Todos os posts'
            href: 404.qmd
          - text: "-"
          - text: 'Projetos'
            href: 404.qmd
          - text: 'Recursos'
            href: 404.qmd
      - text: "Help"
        menu:
          - text: "FAQ"
            href: 404.qmd

    right:
      - icon: envelope
        href: http://eepurl.com/jj-mXo
        text: "Subscribe"
      - icon: github
        href: https://github.com/Mikaelssilva
        text: "Github"
      - icon: linkedin
        href: https://www.linkedin.com/in/mikaelssilva
        text: "Linkedin"

  cookie-consent: 
    type: implied
    style: headline
    palette: dark

  google-analytics: 
    tracking-id: "G-GQLHV05X7L"
    anonymize-ip: false
    
      

  page-footer:
    background: dark
    left: "© 2025 The Machine Learning Engineer - Todos os direitos reservados."
    right:
      - text: 'Contato'
        href: contato.qmd
      - text: 'Política de Privacidade'
        href: privacidade.qmd
      - text: 'Termos de uso'
        href: termo_de_uso.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/mikaelssilva
      - icon: instagram
        href: https://www.instagram.com/mikael.ssilva20/
      - icon: youtube
        href: https://www.youtube.com/channel/UCTev7AuWd_45HArWkeEKf9w

format:
  html:
    theme: 
      - journal
    css: styles.css
    toc: true
    toc-location: right
    code-fold: false
    code-tools: false
    highlight-style: github-dark
    smooth-scroll: true
    page-layout: full
    title-block-banner: true

# Configurações de busca
search: true

# Comentários
comments:
  giscus:
    repo: Mikaelssilva/TheMachineEngineerBlog
    repo-id: "R_kgDOPUVqWg"    
    category: "Comments"
    category-id: "DIC_kwDOPUVqWs4Ctjjy"
    mapping: pathname
    reactions-enabled: true
    theme: prefered_theme