project:
  type: website
  output-dir: docs

website:
  title: "The Machine Learning Engineer"
  reader-mode: true
  
  navbar:
    background: dark
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Subscribe"
        href: http://eepurl.com/jj-mXo

    right:
      - icon: book
        href: conduct.qmd
        text: "Conduta"
      - icon: github
        href: https://github.com/Mikaelssilva
        text: "Github"
      - icon: linkedin
        href: https://www.linkedin.com/in/mikaelssilva
        text: "Linkedin"
      

  page-footer:
    background: dark
    left: "© 2025 The Machine Learning Engineer. Todos os direitos reservados."
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/mikaelssilva
      - icon: instagram
        href: https://www.instagram.com/mikael.ssilva20/
      - icon: github
        href: https://github.com/Mikaelssilva
      - icon: youtube
        href: https://www.youtube.com/channel/UCTev7AuWd_45HArWkeEKf9w

format:
  html:
    theme: 
      - journal
    css: styles.css
    toc: true
    toc-location: right
    code-fold: false
    code-tools: false
    highlight-style: github-dark
    smooth-scroll: true
    page-layout: full
    title-block-banner: true

# Configurações de busca
search: true

# Comentários
comments:
  giscus:
    repo: Mikaelssilva/TheMachineEngineerBlog
    repo-id: "R_kgDOPUVqWg"    
    category: "Comments"
    category-id: "DIC_kwDOPUVqWs4Ctjjy"
    mapping: pathname
    reactions-enabled: true
    theme: prefered_theme