---
title: "Política de Privacidade"
comments: false
page-layout: full
---

Sua privacidade é importante. Esta política explica como informações pessoais são coletadas, usadas e protegidas neste blog.

### Coleta de Informações

Este site pode coletar as seguintes informações:

- Endereço de e-mail, nome e data de nascimentos se você se inscrever na newsletter.
- Informações sobre o navegador e dispositivo, através do Google Analytics

### Uso das Informações

As informações coletadas são utilizadas para:

- Enviar atualizações sobre novos posts (newsletter);
- Melhorar a navegação e experiência do usuário;

### Compartilhamento

Seus dados **não são vendidos ou compartilhados** com terceiros, exceto quando necessário para serviços como a newsletter (Mailchimp).

### Cookies

Este site pode utilizar cookies para melhorar sua experiência. Você pode desativá-los nas configurações do seu navegador.

### Consentimento

Ao navegar neste site, você concorda com esta política de privacidade.
