name: Moderate Giscus Comments
on:
  discussion_comment:
    types: [created]

jobs:
  moderate:
    runs-on: ubuntu-latest
    steps:
      - name: Check for bad words
        uses: actions/github-script@v6
        with:
          script: |
            // Palavras proibidas (strings simples)
            const badWords = [
              // Racismo
              'macaco', 'negrinho', 'branquelo', 'judeu doente', 'cabelo de bombril', 'serviço de preto',
              
              // LGBTfobia
              'veado', 'bicha', 'sapatão', 'viadinho', 'aidético', 'frutinha', 'boiola',
              
              // Machismo
              'vai lavar louça', 'lugar de mulher é', 'feminazi', 'puta', 'cadê o sanduíche',
              
              // Outros
              'deficiente mental', 'retardado', 'vai se matar', 'corno', 'gordo nojento',
              
              // Termos disfarçados (como strings)
              'v3@d0', 'b1ch4', 'm@c4c0'
            ];
            
            // Padrões regex para termos mais complexos
            const regexPatterns = [
              /n[e3]gr[o0]/i,
              /[ck]retin[o0]/i,
              /v[i1][a@]d[o0]/i,
              /b[i1]ch[a@]/i
            ];
            
            // Obtém o texto do comentário
            const commentText = context.payload.comment.body;
            const commentTextLower = commentText.toLowerCase();
            
            console.log('Verificando comentário:', commentText);
            
            let hasProhibitedContent = false;
            let matchedWord = '';
            
            // Verifica palavras proibidas (strings)
            for (const word of badWords) {
              if (commentTextLower.includes(word.toLowerCase())) {
                hasProhibitedContent = true;
                matchedWord = word;
                break;
              }
            }
            
            // Verifica padrões regex
            if (!hasProhibitedContent) {
              for (const pattern of regexPatterns) {
                if (pattern.test(commentText)) {
                  hasProhibitedContent = true;
                  matchedWord = pattern.toString();
                  break;
                }
              }
            }
            
            if (hasProhibitedContent) {
              console.log('Conteúdo proibido encontrado:', matchedWord);
              
              try {
                // Obtém o node_id do comentário para usar com GraphQL
                const commentNodeId = context.payload.comment.node_id;
                
                // Deleta o comentário usando GraphQL
                const deleteResult = await github.graphql(`
                  mutation deleteDiscussionComment($commentId: ID!) {
                    deleteDiscussionComment(input: {id: $commentId}) {
                      clientMutationId
                    }
                  }
                `, {
                  commentId: commentNodeId
                });
                
                console.log('Comentário deletado com sucesso via GraphQL');
                
                // Cria um novo comentário informativo usando GraphQL  
                const discussionNodeId = context.payload.discussion.node_id;
                
                await github.graphql(`
                  mutation addDiscussionComment($discussionId: ID!, $body: String!) {
                    addDiscussionComment(input: {
                      discussionId: $discussionId,
                      body: $body
                    }) {
                      comment {
                        id
                      }
                    }
                  }
                `, {
                  discussionId: discussionNodeId,
                  body: '🚨 **Comentário removido automaticamente**\n\nUm comentário foi removido por violar nossas diretrizes da comunidade. Por favor, mantenha um ambiente respeitoso para todos.\n\n---\n*Esta é uma ação automática do sistema de moderação.*'
                });
                
                console.log('Comentário de notificação criado via GraphQL');
                
              } catch (error) {
                console.error('Erro ao moderar comentário:', error);
                
                // Fallback: Pelo menos registra o problema nos logs do GitHub
                console.log('Tentando alternativa: criar issue para revisão manual');
                
                try {
                  // Cria uma issue para revisão manual como fallback
                  await github.rest.issues.create({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    title: '🚨 Moderação Manual Necessária',
                    body: `**Comentário com conteúdo proibido detectado:**
                    
**Autor:** @${context.payload.comment.user.login}
**Discussion:** #${context.payload.discussion.number}
**Palavra encontrada:** ${matchedWord}
**Data:** ${new Date().toISOString()}

**Comentário original:**
\`\`\`
${context.payload.comment.body}
\`\`\`

**Ação necessária:** Revisar e moderar manualmente.
**Link:** ${context.payload.comment.html_url}`,
                    labels: ['moderation', 'automated']
                  });
                  
                  console.log('Issue de moderação manual criada');
                } catch (issueError) {
                  console.error('Falha ao criar issue de fallback:', issueError);
                }
                
                // Marca como falha para alertar nos logs
                core.setFailed(`Falha na moderação automática: ${error.message}`);
              }
            } else {
              console.log('Comentário aprovado - nenhum conteúdo proibido encontrado');
            }
          github-token: ${{ secrets.GITHUB_TOKEN }}
