name: Simple Comment Moderation

on:
  discussion_comment:
    types: [created]

jobs:
  moderate:
    runs-on: ubuntu-latest
    steps:
      - name: Moderação automática com resposta em thread
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const badWords = [
              'puta', 'merda', 'fdp', 'caralho', 'porra', 'buceta',
              'macaco', 'negrinho', 'veado', 'bicha', 'retardado',
              'vai se matar', 'corno', 'idiota', 'burro'
            ];

            const comment = context.payload.comment;
            const commentText = comment.body.toLowerCase();
            const author = comment.user.login;
            const discussion = context.payload.discussion;
            const discussionNumber = discussion.number;

            console.log(`🔍 Verificando comentário de @${author}...`);
            const foundBadWords = badWords.filter(word =>
              commentText.includes(word.toLowerCase())
            );

            if (foundBadWords.length > 0) {
              console.log(`🚨 Linguagem ofensiva detectada: ${foundBadWords.join(', ')}`);

              const issueBody = `## 🚨 Comentário Inadequado Detectado

**Autor:** @${author}  
**Discussão:** [${discussion.title}](${discussion.html_url})  
**Data:** ${new Date().toLocaleString('pt-BR')}  
**Palavras detectadas:** \`${foundBadWords.join(', ')}\`

**Comentário original:**
> ${comment.body}

🔗 [Ver comentário](${comment.html_url})  
🔗 [Ver discussão completa](${discussion.html_url})

---

**Ações sugeridas:**
- [ ] Revisar o comentário
- [ ] Remover se necessário
- [ ] Alertar o usuário
- [ ] Tomar medidas administrativas

*Issue gerada automaticamente pelo sistema de moderação.*`;

              // Cria uma issue de moderação
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: `🚨 Moderação: Comentário de @${author}`,
                body: issueBody,
                labels: ['moderação', 'urgente'],
                assignees: ['Mikaelssilva']
              });

              // Adiciona reação 👀
              await github.rest.reactions.createForDiscussionComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: comment.id,
                content: 'eyes'
              });

              // Adiciona reação ⚠️
              await github.rest.reactions.createForDiscussionComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: comment.id,
                content: 'warning'
              });

              // Responde diretamente ao comentário
              const reply = `Olá @${author}, este comentário foi marcado automaticamente por conter termos considerados ofensivos.  
Pedimos que mantenha o respeito nas interações. A moderação será feita conforme as regras do blog.`;

              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: discussionNumber,
                body: `> _Comentário de @${author}_\n\n⚠️ ${reply}`
              });

              console.log("✅ Moderação concluída: Issue + resposta enviada.");
            } else {
              console.log('✅ Nenhum termo ofensivo detectado.');
            }
